### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by xmha97** [VincentEngel/VES-Image-Compare#13]
Thanks for this app.
Please add the light theme.

**Comment by VincentEngel** [comment]
Hey @xmha97 ,

thanks for the idea. I added it in https://github.com/VincentEngel/VES-Image-Compare/releases/tag/fdroid-v2.0.6

**Comment by xmha97** [comment]
> Hey @xmha97 ,
> 
> thanks for the idea. I added it in https://github.com/VincentEngel/VES-Image-Compare/releases/tag/fdroid-v2.0.6

Thanks, also please see this issue:

https://github.com/VincentEngel/VES-Image-Compare/issues/14
