### ISSUE TITLE
Follow the Android theme by default

### ISSUE THREAD

**Issue by xmha97** [VincentEngel/VES-Image-Compare#14]
Please follow the Android theme by default.

![IMG_20221116_145209_029.jpg](https://user-images.githubusercontent.com/23485114/202167562-b4280390-4111-4aa9-8c7c-919639dccfc6.jpg)

**Comment by VincentEngel** [comment]
Added in https://github.com/VincentEngel/VES-Image-Compare/releases/tag/fdroid-v2.0.9

**Comment by xmha97** [comment]
Thanks
