### ISSUE TITLE
Disable scroll on landscape mode

### ISSUE THREAD

**Issue by xmha97** [VincentEngel/VES-Image-Compare#15]
Pleaae improve landscape UI and disable scroll:

![Screenshot_2022-11-18-00-09-41-408_com.vincentengelsoftware.vesandroidimagecompare.jpg](https://user-images.githubusercontent.com/23485114/202555177-c4194da9-39aa-4045-983e-c939a7e881e7.jpg)

Thanks.

**Comment by VincentEngel** [comment]
https://github.com/VincentEngel/VES-Image-Compare/releases/tag/fdroid-v2.0.7

**Comment by xmha97** [comment]
Thanks.
