### ISSUE TITLE
Add Save button

### ISSUE THREAD

**Issue by xmha97** [VincentEngel/VES-Image-Compare#19]
Please add the save button.

I have to take a screenshot now.

![Screenshot_2022-11-23-03-04-57-254_com.vincentengelsoftware.vesandroidimagecompare.jpg](https://user-images.githubusercontent.com/23485114/203443042-fa249a5d-1d46-41bf-8dcd-ca6114498971.jpg)

**Comment by VincentEngel** [comment]
Hey @xmha97  What do you expect a save button to do, that is different from taking a screenshot?

**Comment by bigConifer** [comment]
Hey @xmha97, @VincentEngel,

IMHO this App is in the first place one for image comparison and not for creating "collages" 😉

So in the compare modes the images should be displayed as large as possible with as few distracting UI elements as possible. 

To achive that I would also prefer to move the synced zoom button to the home screen (already proposed it here #10). But please do not clutter the compare modes with even more buttons.
In consequence, screenshots would look nice again, too :)

**Comment by bigConifer** [comment]
> Because I have to crop the status bar and navigation bar

For me on Android 9 no system bar is shown. 

However, `FLAG_FULLSCREEN` was deprecated in API level 30. 

https://github.com/VincentEngel/VES-Image-Compare/blob/2846b32f006c604ed42fb36219eb95864a13e4d5/app/src/main/java/com/vincentengelsoftware/androidimagecompare/helper/FullScreenHelper.java#L9-L12

With `WindowInsetsControllerCompat.hide()` and system bars behavior set to `BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE` immersive mode should also work for @xmha97.

**Comment by VincentEngel** [comment]
@bigConifer thanks I will try that 💪

**Comment by VincentEngel** [comment]
Added better fullscreen support with this commit https://github.com/VincentEngel/VES-Image-Compare/commit/a1c4af0bea990aa6660ec3188b7fb42208e96063, but I need to do some more testing bevor creating the next release.

**Comment by VincentEngel** [comment]
Improved fullscreen is in version 2.1.1 https://github.com/VincentEngel/VES-Image-Compare/releases/tag/fdroid-v2.1.1

Therefore I will not add a "Save" button for now.

**Comment by bigConifer** [comment]
Great, thanks @VincentEngel!
