### ISSUE TITLE
Theme doesn't change at runtime

### ISSUE THREAD

**Issue by xmha97** [VincentEngel/VES-Image-Compare#20]
Hi,
The theme does not change at runtime.

https://user-images.githubusercontent.com/23485114/203622384-5ae793c4-5e05-408a-9188-f2afb1726dcf.mp4

Pleaae fix this issue.
Thanks.

**Comment by VincentEngel** [comment]
I don't see how this can be fixed. Because I don't see an option to find the current system theme after the app first onCreate call.

**Comment by VincentEngel** [comment]
Thanks @bigConifer added in next version https://github.com/VincentEngel/VES-Image-Compare/commit/ec3ba351dce3af3f21abded2079e259de92ef07e
