### ISSUE TITLE
Oblique comparison

### ISSUE THREAD

**Issue by xmha97** [VincentEngel/VES-Image-Compare#21]
Please add the oblique comparison.
For example:

![The-pros-and-cons-of-Dark-Mode-Heres-when-to-use-it-and-why.jpg](https://user-images.githubusercontent.com/23485114/203790854-2188a2ea-ed5c-4176-b06e-90aa0045aad5.jpg)

![15daeb9f476a55c12361ca7946fcd690ed6b6cc4_2_1380x784.jpg](https://user-images.githubusercontent.com/23485114/203790878-9c96cd68-946b-4dda-a725-318e398d3c9d.jpg)

Right now I can only use side by side:
![Screenshot_2022-11-24-16-20-24-248_com.vincentengelsoftware.vesandroidimagecompare.jpg](https://user-images.githubusercontent.com/23485114/203791007-11cbeaf2-65e2-4eac-b563-8bf437f19941.jpg)

**Comment by VincentEngel** [comment]
Started work on FullSlideActivity in https://github.com/VincentEngel/VES-Image-Compare/commit/3d1ca59094b701036552d0996f3e8b4b21283043 will not be finished any time soon.

**Comment by VincentEngel** [comment]
Added in https://github.com/VincentEngel/VES-Image-Compare/commit/28afe0f157727534d7d51f7a4d4d8905a750d799 will be part of next version 2.2.5
