### ISSUE TITLE
Rename the app

### ISSUE THREAD

**Issue by xmha97** [VincentEngel/VES-Image-Compare#22]
Please rename the app,
From: "VES - Image and Photo Compare"
To: "VES"
It's too long...
![Screenshot_2022-11-24-16-36-37-504_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/23485114/203791822-a6713939-4c44-4353-8187-bfdaa5ef22e5.jpg)

**Comment by VincentEngel** [comment]
Thank you for your suggestion, but I will not change the name of the App.
