### ISSUE TITLE
Allow zoom in more modes

### ISSUE THREAD

**Issue by di72nn** [VincentEngel/VES-Image-Compare#3]
Allow zoom in the following modes:
* [ ] Overlay Tap.
* [ ] Overlay Slide.
* [ ] Transparent.

Hi! Thank you for developing the app!
I've been comparing photos in a gallery app using something like "overlay tap" ([Simple Gallery](https://f-droid.org/packages/com.simplemobiletools.gallery.pro/) allows to use taps for image switching), but it would really be nice to be able to keep the zoom level when the images are switched.
I'm not sure whether the zoom level and position should be tied between images. Both ways seem to me to be valid use cases, so it would be nice to have a choice.

**Comment by VincentEngel** [comment]
Hey @di72nn thanks for your suggestions, feedback is highly appreciated.

Zooming in "Overlay Tap" I understand. But how do you expect it to work in "Overlay Slide" and "Transparent"? In these modes you have a set background image, which the user can't access. So only the image in the front could be zoomed in. 🤔

**Comment by VincentEngel** [comment]
Features are added in https://github.com/VincentEngel/VES-Image-Compare/releases/tag/fdroid-v1.3

**Comment by di72nn** [comment]
Thank you for your quick response and implementation!
