### ISSUE TITLE
Improve UI for small screens in portrait

### ISSUE THREAD

**Issue by bigConifer** [VincentEngel/VES-Image-Compare#31]
@VincentEngel Following up to https://github.com/VincentEngel/VES-Image-Compare/commit/d2f861b4de4526bc402b8dae2ae9af8ae4b8d0b5, can you please reduce the vertical padding of the app name to get rid of scroll in portrait mode too 🙏

Moreover the resize and rotate buttons are cropped due to small device width. I definitely prefer to have them in one row but don't know how to fix it.

<p>
<img src="https://user-images.githubusercontent.com/64743731/205356145-fa2c7c65-96bc-4c67-a499-e80b86aaf0bd.jpg" width="45%" />
<img src="https://user-images.githubusercontent.com/64743731/205356233-0772f534-3d2f-4cad-8e33-ee8b2ce35d15.jpg" width="45%" />
</p>

**Comment by bigConifer** [comment]
Btw a minor off topic question: is there any reason for the bottom margin added to the fade-in toolbar in overlay transparent and overlay slide mode?
https://github.com/VincentEngel/VES-Image-Compare/blob/ba621f18a01c65fc3bdee26c9833a33515cd1096/app/src/main/res/layout/activity_overlay_transparent.xml#L41-L49

**Comment by VincentEngel** [comment]
I added the padding, because (depending on the rotation) you have the taskbar moving in/out as well. I would like to not have it overlapping.

![d4f05406-c80a-4494-bb78-8d49a1f4f2b1](https://user-images.githubusercontent.com/19281604/205363973-beb006f0-07a1-4368-8d3c-a043aaae99c3.png)

**Comment by VincentEngel** [comment]
What screensize are you using?

**Comment by bigConifer** [comment]
> because (depending on the rotation) you have the taskbar moving in/out as well

Hmm, maybe there is an option to move it up only when the navigation bar moves in.
When there is no navigation bar it looks strange otherwise:
![Screenshot_VES - Image and Photo Compare](https://user-images.githubusercontent.com/64743731/205367748-5bb790f6-4a71-4c0a-8421-9d4adde7ab05.jpg)

**Comment by VincentEngel** [comment]
Thanks for waiting. I will publish an update next week which will change the main_activity for screens <=640dp.

I will created two new Issues to improve main_activity [landscape](https://github.com/VincentEngel/VES-Image-Compare/issues/40) and [portait](https://github.com/VincentEngel/VES-Image-Compare/issues/41).

![360x649screen](https://user-images.githubusercontent.com/19281604/224492120-e77bce89-17e6-4f56-802e-a3cfb035b4f1.png)

https://github.com/VincentEngel/VES-Image-Compare/commit/b17e97a0042406571ddccc5edac2977443085b92
