### ISSUE TITLE
Explanation of icons between images

### ISSUE THREAD

**Issue by lfom** [VincentEngel/VES-Image-Compare#33]
Thanks for the app, it's a nice utility. I didn't find about what the icons between they images do. Probably it's a good idea to add something in the info/help page or when tapping-and-holding.

Regards

![Screenshot_20221204-074326276 (1).jpg](https://user-images.githubusercontent.com/15659999/205486287-664c123f-c9c4-495e-9505-02518647cea0.jpg)

**Comment by VincentEngel** [comment]
Hey thanks for the feedback @lfom ,

in the next release, there will be an info popup if you press down a button https://github.com/VincentEngel/VES-Image-Compare/commit/59394c4406d8bd7dc0655faa867bb350f2463961
