### ISSUE TITLE
Upload APK on the release page

### ISSUE THREAD

**Issue by xmha97** [VincentEngel/VES-Image-Compare#37]
Please upload APK on the release page.
Thanks.

**Comment by rancidfrog** [comment]
Github does it automatically for you, either through actions or gradle.
Also, fdroid now is encouraging reproducible builds so if that design principle us followed you will not have issues of different builds

**Comment by xmha97** [comment]
Can't see APK files on GitHub
I don't use F-Droid because it is signed by f-droid not the developer.

**Comment by VincentEngel** [comment]
Not sure whetehr I will take the time to make reproducible builds working. But I created an issue for that https://github.com/VincentEngel/VES-Image-Compare/issues/43


Currently you can:

1. Download from PlayStore
2. Download from F-Droid Store
3. Download the code and build it yourself

Note: For the current release I added the APK myself, however I can not guarantee that I will always do that. Therefore I encourage you to use one of the three methods noted above.

**Comment by xmha97** [comment]
Thanks 🙏
