### ISSUE TITLE
Accept shared images

### ISSUE THREAD

**Issue by di72nn** [VincentEngel/VES-Image-Compare#4]
Accept imaged that are shared through Android's standard sharing options.

If two images are shared at the same time, it should be quite straightforward, but it would be nice if it would also be possible to share images separately: you look at the images individually (one image on the screen) in a gallery app, you share the current image, you switch to another image in the gallery, you share it, you can compare them in VES Image Compare now.

**Comment by VincentEngel** [comment]
Added in version 1.4 https://github.com/VincentEngel/VES-Image-Compare/releases/tag/fdroid-v1.4
