### ISSUE TITLE
Multiple entries in "recent apps"

### ISSUE THREAD

**Issue by di72nn** [VincentEngel/VES-Image-Compare#5]
The app leaves multiple entries on the "recent apps" screen, probably caused by sharing images to the app.
Let me know if I need to elaborate on the description.

Thanks for the app again :) Never realized I needed something like that until I saw the app on F-Droid :)

**Comment by VincentEngel** [comment]
Hey @di72nn ,

thanks for the kind words and the bug report. I was able to replicate the bug and I will test a fix in the coming days.
