### ISSUE TITLE
Make compare mode selection dialog look better

### ISSUE THREAD

**Issue by VincentEngel** [VincentEngel/VES-Image-Compare#50]

**Comment by di72nn** [comment]
Not sure if I should create a separate issue, but can you please consider making a "default comparison method"? I exclusively use the overlay tap option, and having to find and select that option *every time* gets old really fast.

I can imagine a few ways that may work.

* The "compare" button directly starts the comparison using the last used comparison method. A separate button nearby (maybe an arrow like the one right to the "Close issue" button here on github) would open a comparison method selection dialog. Not exactly an obvious approach, I suppose.
* Same two buttons, but the "compare" button opens the comparison method selection dialog that has some kind of "always use this method" checkbox (or directly starts the comparison if the checkbox was checked previously). The second button could open the selection dialog allowing to uncheck the checkbox. Or the second button should only be used to reset the saved method :thinking: 
* I can also see a use-case where someone would use one comparison mode all the time and only occasionally choose another one without wanting to reset the default. This feels like a dropbox in the settings screen "default comparison mode" with "ask every time" and all the other modes listed. And the second small button on the main screen could be used to choose a one-time mode.

Anyway, thank you for working on the app! I use it almost every time I'm sorting photos on my phone :slightly_smiling_face:
