### ISSUE TITLE
Add a way to save the "resize" option

### ISSUE THREAD

**Issue by di72nn** [VincentEngel/VES-Image-Compare#58]
It seems it resets to "On" every time the app is opened anew. I don't think I use the option in the "on" state at all, so it is kind of annoying.

**Comment by VincentEngel** [comment]
Hey @di72nn thanks for the feedback. I will save it in the preferences so that it won't reset.

**Comment by VincentEngel** [comment]
Will be part of the next version https://github.com/VincentEngel/VES-Image-Compare/commit/f76a69db9f13c2dd5572b2fa0449502f67546a98
