### ISSUE TITLE
[Enhancement] Preserve transparency in Overlay Tap mode

### ISSUE THREAD

**Issue by e-t-l** [VincentEngel/VES-Image-Compare#63]
Consider comparing two PNG images, A and B, where A has a transparent area (e.g. a circular "cutout" in the middle of the image that has 0% opacity).

In Overlay Tap mode, any transparent areas of PNGs become white with 100% opacity. So, overlaying image A over image B results in just image A being visible, with a white circle in the middle of the image.

Instead, the transparent areas should be preserved, so that overlaying A over B results in the user seeing A, with a circular area of image B visible in the middle of it (aka "behind" the transparent area of image A).

Would this be doable?

**Comment by VincentEngel** [comment]
Hey @e-t-l do you maybe have an image I can test with?

**Comment by VincentEngel** [comment]
https://github.com/VincentEngel/VES-Image-Compare/releases/tag/fdroid-v2.2.6
