### ISSUE TITLE
email id on fdroid metadata

### ISSUE THREAD

**Issue by jindam-vani** [VincentEngel/VES-Image-Compare#68]
@VincentEngel 
* **without your explicit consent** email id ```vincentengelsoftware@gmail.com``` given in https://github.com/VincentEngel/VES-Image-Compare#contact was added by me in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.vincentengelsoftware.vesandroidimagecompare.yml)
* email id updated in fdroid metadata will create link on fdroid client
* should i remove it?

**Comment by VincentEngel** [comment]
It's fine. Please keep it. Thank you for taking care of it as well as informing me about it!
