### ISSUE TITLE
FR: 100% zoom level

### ISSUE THREAD

**Issue by Efreak** [VincentEngel/VES-Image-Compare#78]
Currently if you open an image that's smaller than the screen resolution, it refuses it to be larger. If you then try to zoom out, it only adds about 20% margin, then as soon as you lift your fingers it zooms back in to fit the screen again. Please add a mode that does no zoning whatsoever, I'd like to compare two smaller images pixel-for-pixel.

It would also be helpful for this if there was also a toggle for nearest neighbor instead of using whatever smoothing resize algorithm is in place.

For my current images, I got around this with imagemagick (added a border around both images so they were exactly screen resolution, then resized with nearest neighbor to 5x my screen size and saved as lossless PNG file... Not a great way to get around this).

PS: I've been using your app since I first saw it show up on fdroid, and I'd be happy to give a few bucks for it. I recommend turning on GitHub sponsor as it (currently) doesn't have any fees for either side, but play store has a higher reach. This app imo perfectly complements dev.macgyver photo editor and warp labs (both on play store and not oss, unfortunately). It's unfortunate that there's no app that does this well on desktop (or on the web--imgsli is far more limited in functionality, and doesn't allow bypassing file size/type limitations with remote URLs). I used VES a few times on WSA, but Microsoft has now announced it's being shut down next year; hopefully waydroid can figure out running Android apps through WSL instead.

**Comment by VincentEngel** [comment]
Hey @Efreak thanks for your intereset in my App and your suggestions for improvement.

Regarding your first question:

For zooming and other interactions I am using https://github.com/MikeOrtiz/TouchImageView 

I set the max zoom by default to up to 100 (% I think). This is because this value is also used by the library to decide the zoom when you double tap on an image.

You can already open the options menu: Top right gear icon, then settings and there is "max zoom". Can you test whether increasing this value resolves your issue? If not, can you please provide me with the images that cause the issue as well as the adjusted image to solve it? I am not able to reproduce it right now.

There are a few more options I haven't investigated yet, that are modifying the zoom functionality.

Regarding your other comments and issues I will come back to you in 1-2 weeks when I have the time.

**Comment by Efreak** [comment]
This would actually be *minimum* zoom, not *maximum* zoom. It should also be default zoom or a sticky point that zooming stops at temporarily to make it easier. To see this easier, you can open two images that are different sizes, and you'll see that *both images are scaled to fit the screen* (by different amounts). This happens regardless of image resize settings (I've tried setting to original and to automatic, and I've tried manually setting the size for each image to the image's actual size[^1]). I'm looking for a mode with no scaling at all (unless I zoom).

[^1]: this is more difficult because the metadata is blank, at least for webp images. Regardless of xmp/iptc/etc data, I would expect to see things like dimensions, file size, and format there, and possibly filesystem dates if the app can see those. I had to get the image dimensions from my file manager instead. 

I'll attach a made up example here in a few minutes (I'm using a GitHub client that doesn't support uploading). This still doesn't work quite as it should due to VES framing the image, but it's better than the alternative. (Also I used a white canvas instead of black for some reason, which isn't ideal for the image I chose)

**Comment by VincentEngel** [comment]
Thanks I will look into it next week. By default small images are scaled up. You can disable this option under each image, by clicking on the quadrat icon and selecting "original".

**Comment by Efreak** [comment]
Yes, I tried picking original, it doesn't work for me:
![video](https://gistcdn.githack.com/Efreak/df2ba4e38c606a3d025be66f11d26b89/raw/747c01d410529c1955bd6c047775c57b25e70534/VES.webm)

**Comment by VincentEngel** [comment]
Hey @Efreak thanks for your helpful input, images and the video.

I added a new option to change the minZoom value https://github.com/VincentEngel/VES-Image-Compare/commit/e769b423d8446bfbaf7d64a83656580e9037ce65 I will need to do some more testing for different SDKs before publishing it.

I think that will be either this weekend or next weekend.

**Comment by VincentEngel** [comment]
The option of adjusting the minZoom in the settings is part of the new release https://github.com/VincentEngel/VES-Image-Compare/releases/tag/fdroid-v2.2.7
